export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const SIGNIN_EXITOSO = 'SIGNIN_EXITOSO';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';